# _config.yml
# This is the main configuration file for your Jekyll site
# It defines site-wide variables and settings that Jekyll uses to generate your static site
# Modify these settings to customize your portfolio website

# Site settings
title: "Isamu Thung" # Your name or the title of your portfolio
email: "isamuthung@gmail.com" # Your email address
description: >- # This means to ignore newlines until the next key
  A portfolio website showcasing my work, writings, and projects.
  Built with Jekyll and hosted on GitHub Pages.
baseurl: "/Isamu" # The subpath of your site, e.g. /blog (Check if this is correct for GitHub Pages)
url: "https://isamuthung.com" # The base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Collections settings
collections:
  writings:
    output: true
    permalink: /writings/:path/
  
  journal:
    output: true
    permalink: /journal/:path/

  projects:
    output: true
    permalink: /projects/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "writings"

  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"

  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
  - gemfiles
  - README.md
